/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dnebinger.webstory.uad.anonymizer;

import com.dnebinger.webstory.model.WebStory;
import com.dnebinger.webstory.service.WebStoryLocalService;
import com.dnebinger.webstory.uad.constants.webstoryUADConstants;

import com.liferay.asset.kernel.model.AssetEntry;
import com.liferay.asset.kernel.service.AssetEntryLocalService;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the web story UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link WebStoryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseWebStoryUADAnonymizer
	extends DynamicQueryUADAnonymizer<WebStory> {

	@Override
	public void autoAnonymize(
			WebStory webStory, long userId, User anonymousUser)
		throws PortalException {

		if (webStory.getUserId() == userId) {
			webStory.setUserId(anonymousUser.getUserId());
			webStory.setUserName(anonymousUser.getFullName());

			autoAnonymizeAssetEntry(webStory, anonymousUser);
		}

		if (webStory.getStatusByUserId() == userId) {
			webStory.setStatusByUserId(anonymousUser.getUserId());
			webStory.setStatusByUserName(anonymousUser.getFullName());
		}

		webStoryLocalService.updateWebStory(webStory);
	}

	@Override
	public void delete(WebStory webStory) throws PortalException {
		webStoryLocalService.deleteStory(webStory);
	}

	@Override
	public Class<WebStory> getTypeClass() {
		return WebStory.class;
	}

	protected void autoAnonymizeAssetEntry(
		WebStory webStory, User anonymousUser) {

		AssetEntry assetEntry = fetchAssetEntry(webStory);

		if (assetEntry != null) {
			assetEntry.setUserId(anonymousUser.getUserId());
			assetEntry.setUserName(anonymousUser.getFullName());

			assetEntryLocalService.updateAssetEntry(assetEntry);
		}
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return webStoryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return webstoryUADConstants.USER_ID_FIELD_NAMES_WEB_STORY;
	}

	protected AssetEntry fetchAssetEntry(WebStory webStory) {
		return assetEntryLocalService.fetchEntry(
			WebStory.class.getName(), webStory.getWebStoryId());
	}

	@Reference
	protected AssetEntryLocalService assetEntryLocalService;

	@Reference
	protected WebStoryLocalService webStoryLocalService;

}